[package]
name = "safe-lang"
version = "1.0.0"
edition = "2024"

[[bin]]
name = "safe"
path = "src/main.rs"

[dependencies]
nom = "7.1.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
